Add elixir lang support
kotct/dot pull request #33
Opened 2017-03-13 18:26 UTC by samontea

Elixir is a pretty cool language. We should have support for it by default. 

⚗⚗⚗

2017-03-13 18:34 UTC, rye requested changes
Almost there, but you also need to add `elixir` to the list in `language-hub.el` to have the system actually load this.

2017-03-13 18:34 UTC, rye commented on .emacs.d/lisp/package/dependencies.el
> +    elixir-mode
Put a comment here (e.g. `;; for editing Elixir code`)

2017-03-13 18:34 UTC, rye commented on .emacs.d/lisp/code/languages/elixir.el
> +(provide 'elixir-configuration)
Since your file is named `elixir`, you should provide `'elixir`.

2017-03-13 18:40 UTC, rye commented on .emacs.d/lisp/code/languages/language-hub.el
> +    elixir
Alphabetize?

2017-03-13 18:44 UTC, rye approved these changes

2017-03-13 18:44 UTC, rye approved these changes
LGTM.

2017-03-13 18:45 UTC, rye commented
Since @cg505 is probably busy because he's overseas at the moment, I'll go ahead and merge this lil' guy. Thanks, @samontea! 🎉

2017-03-13 18:46 UTC, merged

2017-05-07 23:53 UTC, cg505 commented
ty @rye